
# Define services
services:

  # BackendAPI
  backend:
    image: aurel/ticket-management-system-backend
    ports:
      - "8080:8080"
    restart: always
    links:
      - authapi
      - loggingapi
    environment:
      - "spring.profiles.active=prod"
    networks:
      network:
        ipv4_address: 10.5.0.4

  # AuthApi
  authapi:
    image: aurel/ticket-management-system-authapi
    ports:
      - "8081:8081"
    restart: always
    environment:
      - "spring.profiles.active=prod"
    networks:
      network:
        ipv4_address: 10.5.0.2

  # LoggingApi
  loggingapi:
    image: aurel/ticket-management-system-loggingapi
    ports:
      - "8082:8082"
    restart: always
    environment:
      - "spring.profiles.active=prod"
    networks:
      network:
        ipv4_address: 10.5.0.3
      
networks:
  network:
    driver: bridge
    ipam:
      config:
         - subnet: 10.5.0.0/16