
# Define services
services:

  # BackendAPI
  backend:
    image: aurel/ticket-management-system-backend
    ports:
      - "8080:8080"
    restart: always
    links:
      - authapi
      - loggingapi
    environment:
      - "spring.profiles.active=prod"
      - "authapi.url=http://localhost:8081"
      - "loggingapi.url=http://localhost:8082"

  # AuthApi
  authapi:
    image: aurel/ticket-management-system-authapi
    ports:
      - "8081:8081"
    restart: always
    environment:
      - "spring.profiles.active=prod"

  # LoggingApi
  loggingapi:
    image: aurel/ticket-management-system-loggingapi
    ports:
      - "8082:8082"
    restart: always
    environment:
      - "spring.profiles.active=prod"
